<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="booking_status.aspx.cs" Inherits="Restaurant_Website.booking_status" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentBody" runat="server">
    <p>
        <asp:Label ID="Bookings" runat="server" Font-Bold="True" ForeColor="#0033CC"></asp:Label>
    </p>
    <div>

        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ORDERID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2">
            <Columns>
                <asp:BoundField DataField="ORDERID" HeaderText="ORDERID" InsertVisible="False" ReadOnly="True" SortExpression="ORDERID" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Phone" HeaderText="Phone" SortExpression="Phone" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="TableNumber" HeaderText="TableNumber" SortExpression="TableNumber" />
                <asp:BoundField DataField="StartTime" HeaderText="StartTime" SortExpression="StartTime" />
                <asp:BoundField DataField="EndTime" HeaderText="EndTime" SortExpression="EndTime" />
                <asp:BoundField DataField="Attendees" HeaderText="Attendees" SortExpression="Attendees" />
                <asp:BoundField DataField="Comments" HeaderText="Comments" SortExpression="Comments" />
            </Columns>
            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=DESKTOP-HOLDA9M\SQLEXPRESS1;Initial Catalog=login;Integrated Security=True" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [ORDERID], [Name], [Phone], [Email], [TableNumber], [StartTime], [EndTime], [Attendees], [Comments] FROM [Table_Booking] WHERE ([Username] = @Username)" DeleteCommand="DELETE from Table_Booking where ORDERID = @ORDERID">
            <SelectParameters>
                <asp:SessionParameter DefaultValue="UserID" Name="Username" SessionField="UserID" Type="String" />
            </SelectParameters>
        </asp:SqlDataSource>

    </div>
</asp:Content>
